### ISSUE TITLE
After upgrading to Ruby 2.6, it throws "uninitialized constant Upsert::Connection::PG_Connection"

### ISSUE THREAD

**Issue by rajgurung** [seamusabshere/upsert#113] opened 2019-01-02 15:04 UTC
Upgrade Ruby to `2.6`, and running Rspec it comes up with ` NameError:
       uninitialized constant Upsert::Connection::PG_Connection::Postgresql`.

**Comment by searls** [comment] 2019-01-06 15:08
Just saw this subtly break one of my scheduled processes and was having a hell of a time figuring out the cause. Thanks for the assist 💚

**Comment by ankane** [comment] 2019-03-27 09:15
Note to future readers: until #114 is merged, you can add this line:

```rb
require 'upsert/connection/postgresql'
```

before

```rb
require 'upsert/active_record_upsert'
```

**Comment by pnomolos** [comment] 2019-05-21 17:08
Hi everyone!  My apologies that it's taken so long to get back to this.  Please use the workaround noted by @ankane (https://github.com/seamusabshere/upsert/issues/113#issuecomment-477053456) until I can everything sorted.  Of course Ruby 2.6 break basically everything all the way down, so it's a lot more complicated than just pushing out this fix.  I want to make sure the gem is in proper shape before it gets a public release.

**Comment by pnomolos** [comment] 2019-05-31 22:39
It's commmmmmmmmmiiiiiiinnnnnng ... https://github.com/seamusabshere/upsert/pull/115

**Closed** 2019-06-07 16:14 UTC
